<a href="https://colab.research.google.com/github/24cse134preetisubudhi-ai/DMDW-Experiment-1/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/Book2.csv')

In [37]:
df

   C:\Users\student\Desktop\24CSE134 Name  marks
0                                  1    a     45
1                                  2    b     67
2                                  3    c     78
3                                  4    d     98
4                                  5    e     56
5                                  6    f     47
6                                  7    g     89
7                                  8    h     95
8                                  9    i     34
9                                 10    j     78

In [38]:
df.head()

   C:\Users\student\Desktop\24CSE134 Name  marks
0                                  1    a     45
1                                  2    b     67
2                                  3    c     78
3                                  4    d     98
4                                  5    e     56

In [39]:
df.tail()

   C:\Users\student\Desktop\24CSE134 Name  marks
5                                  6    f     47
6                                  7    g     89
7                                  8    h     95
8                                  9    i     34
9                                 10    j     78

In [40]:
df.head(7)

   C:\Users\student\Desktop\24CSE134 Name  marks
0                                  1    a     45
1                                  2    b     67
2                                  3    c     78
3                                  4    d     98
4                                  5    e     56
5                                  6    f     47
6                                  7    g     89

In [41]:
df.tail(6)

   C:\Users\student\Desktop\24CSE134 Name  marks
4                                  5    e     56
5                                  6    f     47
6                                  7    g     89
7                                  8    h     95
8                                  9    i     34
9                                 10    j     78

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   C:\Users\student\Desktop\24CSE134  10 non-null     int64
 1   Name                               10 non-null     object
 2   marks                              10 non-null     int64
dtypes: int64(2), object(1)
memory usage: 372.0+ bytes

In [43]:
df.describe()

       C:\Users\student\Desktop\24CSE134      marks
count                           10.00000  10.000000
mean                             5.50000  68.700000
std                              3.02765  22.450192
min                              1.00000  34.000000
25%                              3.25000  49.250000
50%                              5.50000  72.500000
75%                              7.75000  86.250000
max                             10.00000  98.000000

In [44]:
df.shape

(10, 3)

In [45]:
df.columns

Index(['C:\Users\student\Desktop\24CSE134', 'Name', 'marks'], dtype='object')

In [46]:
df.dtypes

C:\Users\student\Desktop\24CSE134     int64
Name                                 object
marks                                 int64
dtype: object

In [47]:
df.isnull()

   C:\Users\student\Desktop\24CSE134   Name  marks
0                              False  False  False
1                              False  False  False
2                              False  False  False
3                              False  False  False
4                              False  False  False
5                              False  False  False
6                              False  False  False
7                              False  False  False
8                              False  False  False
9                              False  False  False

In [48]:
df.iloc[0]

C:\Users\student\Desktop\24CSE134     1
Name                                  a
marks                                45
Name: 0, dtype: object

In [49]:
df.loc[0]

C:\Users\student\Desktop\24CSE134     1
Name                                  a
marks                                45
Name: 0, dtype: object